services:
  postgres:
    image: postgres:16-alpine
    container_name: bd1_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tarjetas_circulacion
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/inserts.sql:/docker-entrypoint-initdb.d/02_inserts.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tarjetas_circulacion"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
